FROM nginx:alpine
# installing nginx-extras
# RUN apk add --no-cache nginx-extras
# ADD nginx/default.conf /etc/nginx/conf.d
# ADD nginx/default.conf ./conf.d/default.conf
# COPY nginx/default.conf /etc/nginx/conf.d/default.conf
