// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("PostAPic_Test_Suite", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("resetdb", async function () {
    await driver.get("http://localhost:8080/resetdb.php");
    await driver.findElement(By.css("html")).click();
    await driver.findElement(By.css("html")).click();
    await driver.close();
  });
  it("create_login_delete_account", async function () {
    await driver.get("http://localhost:8080/resetdb.php");
    await driver.get("http://localhost:3000/");
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.findElement(By.css(".MuiButton-outlined")).click();
    await driver.findElement(By.linkText("Register")).click();
    await driver.findElement(By.id("firstName")).click();
    await driver.findElement(By.id("firstName")).sendKeys("aaron");
    await driver.findElement(By.id("lastName")).click();
    await driver.findElement(By.id("lastName")).sendKeys("collins");
    await driver
      .findElement(By.id("email"))
      .sendKeys("aaron777collins@gmail.com");
    await driver.findElement(By.id("username")).sendKeys("aaron7c");
    await driver.findElement(By.id("password")).sendKeys("aaron13579");
    await driver.findElement(By.css(".MuiButton-containedPrimary")).click();
    await driver.findElement(By.css(".MuiButton-outlined")).click();
    await driver.findElement(By.id("username")).sendKeys("aaron7c");
    await driver.findElement(By.id("password")).sendKeys("aaron13579");
    await driver
      .findElement(By.css('.MuiButton-containedPrimary[type="submit"]'))
      .click();

    await driver.wait(until.elementLocated(By.css(".MuiAvatar-root")), 5000);
    await driver.findElement(By.css(".MuiAvatar-root")).click();

    await driver.wait(until.elementLocated(By.linkText("Profile")), 5000);
    await driver.findElement(By.linkText("Profile")).click();

    await driver.wait(
      until.elementLocated(By.css(".MuiButton-contained")),
      5000
    );
    await driver.findElement(By.css(".MuiButton-contained")).click();

    await driver.wait(until.elementLocated(By.id("ask-confirm-btn")), 5000);
    await driver.findElement(By.id("ask-confirm-btn")).click();

    await driver.close();
  });
  it("create_account_create_post_like_unlike_comment_delete_comment", async function () {
    await driver.get("http://localhost:8080/resetdb.php");
    await driver.get("http://localhost:3000/");
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.findElement(By.css(".MuiButton-outlined")).click();
    await driver.findElement(By.linkText("Register")).click();
    await driver.findElement(By.id("firstName")).click();
    await driver.findElement(By.id("firstName")).sendKeys("aaron");
    await driver.findElement(By.id("lastName")).click();
    await driver.findElement(By.id("lastName")).sendKeys("collins");
    await driver
      .findElement(By.id("email"))
      .sendKeys("aaron777collins@gmail.com");
    await driver.findElement(By.id("username")).sendKeys("aaron7c");
    await driver.findElement(By.id("password")).sendKeys("aaron13579");
    await driver.findElement(By.css(".MuiButton-containedPrimary")).click();
    await driver.findElement(By.css(".MuiButton-outlined")).click();
    await driver.findElement(By.id("username")).sendKeys("aaron7c");
    await driver.findElement(By.id("password")).sendKeys("aaron13579");
    await driver.wait(
      until.elementLocated(
        By.css('.MuiButton-containedPrimary[type="submit"]')
      ),
      5000
    );
    await driver
      .findElement(By.css('.MuiButton-containedPrimary[type="submit"]'))
      .click();
    await driver.findElement(By.css(".MuiButton-root:nth-child(3)")).click();
    await driver.findElement(By.id(":r1:")).click();
    await driver.findElement(By.id(":r1:")).sendKeys("test post");
    await driver.findElement(By.id(":r3:")).click();
    await driver.findElement(By.id(":r3:")).sendKeys("1234");
    await driver
      .findElement(By.id("contained-button-file"))
      .sendKeys("C:\\comp2707uwinserver\\project\\photos\\postapic.png");
    await driver
      .findElement(By.css(".MuiButtonBase-root:nth-child(5)"))
      .click();

    await driver.wait(until.elementLocated(By.css(".post-image > img")), 5000);
    await driver.findElement(By.css(".post-image > img")).click();
    await driver.findElement(By.css(".overlay-image")).click();

    await driver.findElement(By.css(".like-button")).click();

    await driver.wait(until.elementLocated(By.css(".MuiAvatar-root")), 5000);
    await driver.findElement(By.css(".MuiButton-containedSecondary")).click();

    await driver.findElement(By.id(":r3:")).click();
    await driver.findElement(By.id(":r3:")).sendKeys("test");
    await driver.findElement(By.css(".comment-button")).click();

    await driver.wait(
      until.elementLocated(By.css(".comment-header path")),
      5000
    );
    await driver.findElement(By.css(".comment-header path")).click();

    await driver.wait(until.elementLocated(By.css("#ask-confirm-btn")), 5000);
    await driver.findElement(By.css("#ask-confirm-btn")).click();

    await driver.wait(until.elementLocated(By.css(".MuiAvatar-root")), 5000);
    await driver.findElement(By.css(".MuiAvatar-root")).click();
    await driver.findElement(By.linkText("Logout")).click();
    await driver.close();
  });
  it("create_second_account_login_follow_first_account_like_comment_logout_login_admin_delete_both_accounts_logout", async function () {
    await driver.get("http://localhost:3000/");
    await driver.manage().window().setRect({ width: 1024, height: 768 });
    await driver.findElement(By.css(".MuiButton-outlined")).click();
    await driver.findElement(By.linkText("Register")).click();
    await driver.findElement(By.id("firstName")).click();
    await driver.findElement(By.id("firstName")).sendKeys("aaron");
    await driver.findElement(By.id("lastName")).click();
    await driver.findElement(By.id("lastName")).sendKeys("collins");
    await driver
      .findElement(By.id("email"))
      .sendKeys("aaron7772collins@gmail.com");
    await driver.findElement(By.id("username")).sendKeys("aaron7c2");
    await driver.findElement(By.id("password")).sendKeys("aaron13579");
    await driver.findElement(By.css(".MuiButton-containedPrimary")).click();
    await driver.findElement(By.css(".MuiButton-outlined")).click();
    await driver.findElement(By.id("username")).sendKeys("aaron7c2");
    await driver.findElement(By.id("password")).sendKeys("aaron13579");
    await driver.wait(
      until.elementLocated(
        By.css('.MuiButton-containedPrimary[type="submit"]')
      ),
      5000
    );
    await driver
      .findElement(By.css('.MuiButton-containedPrimary[type="submit"]'))
      .click();
    await driver.wait(
      until.elementLocated(By.css(".MuiButton-text:nth-child(2)")),
      5000
    );
    await driver.findElement(By.css(".MuiButton-text:nth-child(2)")).click();
    await driver.findElement(By.id(":r1:")).click();
    await driver.findElement(By.id(":r1:")).sendKeys("aaron7c");

    await driver.wait(
      until.elementLocated(By.css("#follow-button-aaron7c")),
      100000
    );
    await driver.findElement(By.css("#follow-button-aaron7c")).click();
    await driver.wait(
      until.elementLocated(
        By.css(".MuiListItem-root:nth-child(1) .username-header")
      ),
      5000
    );
    await driver
      .findElement(By.css(".MuiListItem-root:nth-child(1) .username-header"))
      .click();

    await driver.wait(until.elementLocated(By.css(".like-button")), 5000);
    await driver.findElement(By.css(".like-button")).click();
    await driver.wait(until.elementLocated(By.css(".unlike-button")), 5000);
    await driver.findElement(By.css(".unlike-button")).click();

    await driver.wait(until.elementLocated(By.css(".MuiInputBase-root")), 5000);
    await driver.findElement(By.css(".MuiInputBase-root")).click();
    await driver.findElement(By.id(":r5:")).sendKeys("test!");
    await driver.findElement(By.css(".comment-button")).click();

    await driver.wait(
      until.elementLocated(By.css(".MuiIconButton-sizeMedium path")),
      5000
    );
    await driver.findElement(By.css(".MuiIconButton-sizeMedium path")).click();

    await driver.wait(until.elementLocated(By.css("#ask-confirm-btn")), 5000);
    await driver.findElement(By.css("#ask-confirm-btn")).click();

    await driver.wait(until.elementLocated(By.css(".like-button")), 5000);
    await driver.findElement(By.css(".like-button")).click();

    await driver.wait(until.elementLocated(By.css(".MuiAvatar-root")), 5000);
    await driver.findElement(By.css(".MuiAvatar-root")).click();

    await driver.wait(until.elementLocated(By.linkText("Logout")), 5000);
    await driver.findElement(By.linkText("Logout")).click();

    await driver.findElement(By.css(".MuiButton-outlined")).click();

    await driver.findElement(By.css(".MuiPaper-elevation3")).click();
    await driver.findElement(By.id("username")).sendKeys("admin");
    await driver.findElement(By.id("password")).sendKeys("admin");

    await driver.findElement(By.css(".MuiButton-containedPrimary")).click();

    await driver.wait(
      until.elementLocated(By.css(".MuiButton-text:nth-child(2)")),
      5000
    );
    await driver.findElement(By.css(".MuiButton-text:nth-child(2)")).click();

    await driver.findElement(By.id(":r1:")).click();
    await driver.findElement(By.id(":r1:")).sendKeys("aaron7c");
    await driver.wait(
      until.elementLocated(
        By.css(".MuiListItem-root:nth-child(1) .username-header")
      ),
      5000
    );
    await driver
      .findElement(By.css(".MuiListItem-root:nth-child(1) .username-header"))
      .click();

    await driver.wait(
      until.elementLocated(By.css(".MuiButton-containedError")),
      5000
    );
    await driver.findElement(By.css(".MuiButton-containedError")).click();

    await driver.wait(until.elementLocated(By.css("#ask-confirm-btn")), 5000);
    await driver.findElement(By.css("#ask-confirm-btn")).click();

    await driver.findElement(By.css(".MuiButton-root:nth-child(2)")).click();
    await driver.findElement(By.id(":r1:")).click();
    await driver.findElement(By.id(":r1:")).sendKeys("aaron7c");
    await driver.wait(until.elementLocated(By.css(".username-header")), 5000);
    await driver.findElement(By.css(".username-header")).click();
    await driver.wait(
      until.elementLocated(By.css(".MuiButton-containedError")),
      5000
    );

    await driver.findElement(By.css(".MuiButton-containedError")).click();
    await driver.wait(until.elementLocated(By.css("#ask-confirm-btn")), 5000);
    await driver.findElement(By.css("#ask-confirm-btn")).click();
    await driver.findElement(By.css(".MuiButton-root:nth-child(2)")).click();
    await driver.findElement(By.css(".MuiAvatar-root")).click();
    await driver.findElement(By.linkText("Logout")).click();
  });
  it('admin', async function() {
    await driver.get("http://localhost:8080/resetdb.php")
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1024, height: 768 })
    await driver.findElement(By.css(".MuiButton-outlined")).click()
    await driver.findElement(By.id("username")).sendKeys("admin")
    await driver.findElement(By.id("password")).sendKeys("admin")
    await driver.findElement(By.css(".MuiButton-containedPrimary[type=\"submit\"]")).click()
    await driver.wait(until.elementLocated(By.id("Admin-btn-navbar2")), 5000)
    await driver.findElement(By.id("Admin-btn-navbar2")).click()
    await driver.wait(until.elementLocated(By.css(".recharts-wrapper > .recharts-surface")), 5000)
    await driver.findElement(By.css(".recharts-wrapper > .recharts-surface")).click()
    await driver.wait(until.elementLocated(By.css(".MuiAvatar-root")), 5000)
    await driver.findElement(By.css(".MuiAvatar-root")).click()
    await driver.findElement(By.id("Logout-btn-navbar3")).click()
    await driver.close()
  })
});
